version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: React
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
      REACT_APP_PROXY_HOST: "http://backend:8000"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: Django
    depends_on:
      - db
    restart: unless-stopped
    environment:
      # Django settings
      SECRET_KEY: "NAuBBLMAZQzPT5NxX4G669TX9FaZMLdR"
      MYSQL_USERNAME: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_HOST: "db"
      MYSQL_PORT: "3306"
      MYSQL_DATABASE: "django"
      CORS_ORIGIN_WHITELIST: "http://localhost:3000"
      ALLOWED_HOSTS: "backend"
  db:
    image: mysql:5.7
    container_name: MySQL
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "django"
    ports:
      - "3306:3306"
    volumes:
      - "./data/mysql:/var/lib/mysql"