version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Django
    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      # Django settings
      SECRET_KEY: "NAuBBLMAZQzPT5NxX4G669TX9FaZMLdR"
      MYSQL_USERNAME: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_HOST: "db"
      MYSQL_PORT: "3306"
      MYSQL_DATABASE: "django"
  db:
    image: mysql:5.7
    container_name: MySQL
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "django"
    ports:
      - "3306:3306"
    volumes:
      - "./data/mysql:/var/lib/mysql"